[technote]
id = "SITCOMTN-144"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-144.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-144"
github_default_branch = "main"
date_created = 2024-10-28T23:18:22Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Chris"
name.family = "Suberlak"
internal_id = "suberlakc"

[[technote.authors.affiliations]]
name = "University of Washington"
internal_id = "Washington"
address = "Dept. of Astronomy, Box 351580, Seattle, WA 98195, USA"
